deck = [
  // Major Arcana
  {
    name: 'The Fool',
    rs: 'O',
    upRight: 'New Beginings, Innocence, Adventure',
    reversed: 'Recklessness, Fearlessness, Risk',
    url: 'https://cdn.pixabay.com/photo/2021/02/15/07/52/the-fool-6016940_1280.jpg',
  },
  {
    name: 'The Magician',
    rs: 'I',
    upRight: 'Willpower, Creation, Manifestation',
    reversed: 'Manipulation, Illusion',
    url: 'https://cdn.pixabay.com/photo/2021/04/05/22/42/the-magician-6154763_1280.jpg',
  },
  {
    name: 'The High Priestess',
    rs: 'II',
    upRight: 'Intuitive, Unconscious, Devine Feminine',
    reversed: 'Repressed Feelings, Withdrawl, Silence',
    url: 'https://cdn.pixabay.com/photo/2021/04/05/22/42/the-high-priestess-6154767_1280.jpg',
  },
  {
    name: 'The Empress',
    rs: 'III',
    upRight: 'Femininity, Nurturing, Fertility, Abundance',
    reversed: 'Dependence, Smothering, Emptiness',
    url: 'https://cdn.pixabay.com/photo/2021/04/05/22/42/the-empress-6154768_1280.jpg',
  },
  {
    name: 'The Emperor',
    rs: 'IV',
    upRight: 'Authority, Structure, A Father Figure',
    reversed: 'Excessive control, rigidity, domination',
    url: 'https://media.istockphoto.com/photos/the-emperor-tarot-card-picture-id506891666',
  },
  {
    name: 'The Heirophant',
    rs: 'V',
    upRight: 'Spiritual Wisdom, Tradition, Conformity, Morality, Ethics',
    reversed: 'Rebellion, Subversiveness, Freedom, Personal Beliefs',
    url: 'https://cdn.pixabay.com/photo/2021/02/15/07/53/hierophant-6016942_1280.jpg',
  },
  {
    name: 'The Lovers',
    rs: 'VI',
    upRight: 'Love, Harmony, Partnerships, Choices',
    reversed: 'Disbalance, One-Sidedness, Disharmony',
    url: 'https://cdn.pixabay.com/photo/2021/03/18/02/19/tarot-cards-6103697_1280.jpg',
  },
  {
    name: 'The Chariot',
    rs: 'VII',
    upRight: 'Direction, Control, Willpower, Determination, Success, Action',
    reversed: 'Lack of Control, Opposition, Lack of Direction, Self-Discipline',
    url: 'https://cdn.pixabay.com/photo/2021/02/15/07/46/chariot-6016921_1280.jpg',
  },
  {
    name: 'Strength',
    rs: 'VIII',
    upRight: 'Strength, Courage, Compassion, Focus, Persuasion, Influence',
    reversed: 'Self-Doubt, Weakness, Insecurity, Low Energy, Raw Emotion',
    url: 'https://cdn.pixabay.com/photo/2021/04/05/22/43/strength-6154776_1280.jpg',
  },
  {
    name: 'The Hermit',
    rs: 'IX',
    upRight: 'Wisdom, Soul Searching, Solitude, Spiritual Enlightenment, Receiving or Giving Guidance',
    reversed: 'Loneliness, Isolation, Paranoia, Sadness, Being Overcome or Paralyzed by Fear',
    url: 'https://cdn.pixabay.com/photo/2021/02/15/07/52/hermit-6016941_1280.jpg',
  },
  {
    name: 'Wheel of Fortune',
    rs: 'X',
    upRight: 'Chance, Destiny and Fate, Karma, Turning Points, Life Cycles',
    reversed: 'Upheaval, Lousy Luck, Unwelcome Change, Setbacks, External Forces',
    url: 'https://cdn.pixabay.com/photo/2021/05/13/06/38/tarot-6249967_1280.jpg',
  },
  {
    name: 'Justice',
    rs: 'XI',
    upRight: 'Fairness, Integrity, Legal Disputes, Cause and Effect, Life Lessons',
    reversed: 'Injustice, Dishonesty, Failure to Take Responsibility, Deceitful Practices, Negative Karma',
    url: 'https://cdn.pixabay.com/photo/2021/05/13/06/38/tarot-6249968_1280.jpg',
  },
  {
    name: 'The Hanged Man',
    rs: 'XII',
    upRight: 'Letting Go, Sacrificing, Pausing to Reflect, Uncertainty, Spiritual Development',
    reversed: '	Discontentment, Stagnation, Negative Patterns, No Solution, Fear of Sacrifice',
    url: 'https://cdn.pixabay.com/photo/2021/02/15/07/52/hanged-man-6016939_1280.jpg',
  },
  {
    name: 'Death',
    rs: 'XIII',
    upRight: 'Ending of a Cycle, Transitions, Getting Rid of Excess, Powerful Movement, Resolutions',
    reversed: 'Resisting Change, Fear of New Beginnings, Dependency, Repeating Negative Patterns',
    url: 'https://cdn.pixabay.com/photo/2021/03/18/02/32/tarot-cards-6103718_1280.jpg',
  },
  {
    name: 'Temperance',
    rs: 'XIV',
    upRight: 'Balance, Moderation, Good Health, Cooperating with Others, Finding Solutions',
    reversed: 'Imbalance, Discord, Hastiness, Overindulgence, Risky Behavior',
    url: 'https://cdn.pixabay.com/photo/2021/02/15/07/42/temperance-6016917_1280.jpg',
  },
  {
    name: 'The Devil',
    rs: 'XV',
    upRight: 'Material Focus, Trapped in Bondage, Addictions and Depression, Negative Thinking, Betrayal',
    reversed: 'Overcoming Addiction, Independence, Reclaiming Power, Detachment, Freedom',
    url: '',
  },
  {
    name: 'The Tower',
    rs: 'XVI',
    upRight: 'Intense and Sudden Change, Release, Painful Loss, Tragedy, Revelation',
    reversed: 'Resisting Change, Avoiding Tragedy, A Narrow Escape, Delaying What is Inevitable',
    url: 'https://cdn.pixabay.com/photo/2021/03/18/02/20/tarot-cards-6103701_1280.jpg',
  },
  {
    name: 'The Star',
    rs: 'XVII',
    upRight: 'Hope, Renewal, Creativity and Inspiration, Generosity, Healing',
    reversed: 'Despair, Lack of Hope, Creative Block, Boredom, Focusing on the Negative',
    url: 'https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249976_1280.jpg',
  },
  {
    name: 'The Moon',
    rs: 'XVIII',
    upRight: 'Fear, anxiety, confusion, delusion, risk',
    reversed: 'Overcoming Fear, Finding the Truth, Conquering Anxiety, Gaining Clarity',
    url: 'https://cdn.pixabay.com/photo/2021/03/18/02/20/tarot-cards-6103698_1280.jpg',
  },
  {
    name: 'The Sun',
    rs: 'XIX',
    upRight: 'Happiness, Fertility, Success, Optimism, Truth',
    reversed: 'Sadness, Procrastination, Pessimism, Lies, Failure',
    url: 'https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249979_1280.jpg',
  },
  {
    name: 'Judgement',
    rs: 'XX',
    upRight: 'Reflection, Inner Calling, Reckoning, Awakening, Rebirth, Absolution',
    reversed: 'Feeling Down, Self-Doubt, Missing the Call Fearlessness',
    url: 'https://cdn.pixabay.com/photo/2021/10/06/23/00/judgement-6686819_1280.jpg',
  },
  {
    name: 'The World',
    rs: 'XXI',
    upRight: 'Fulfillment, Harmony, Completion, Integration, Travel, Unity',
    reversed: 'Incompletion, Shortcuts, Delays, Emptiness',
    url: 'https://cdn.pixabay.com/photo/2021/10/06/23/00/the-world-6686820_1280.jpg',
  },
  // Minor Arcana
  {
    name: 'Ace of Wands',
    rs: 'Wands',
    upRight: 'Great news related to new beginings, Everything is falling into place, See the Potential, Having a new idea or inspiration',
    reversed: 'Lack of passion, Wanted to be more excited, Want to fix things, Feeling down, not motivated, lacking direction',
    url: '',
  },
  {
    name: 'Two of Wands',
    rs: 'Wands',
    upRight: 'Waiting, Planning, Faith in the Future, Ambitious, Acheivements, Ownership, Success',
    reversed: 'Delays, Losing Interest, Doubt, Abuse of Power',
    url: '',
  },
  {
    name: 'Three of Wands',
    rs: 'Wands',
    upRight: 'Success, Progress, New Ideas, Good Advice, Travel, Expansion, Hopeful',
    reversed: 'Overly Confident, Delays, Lack of Plans, Feeling Hopeless, Feeling Blocked',
    url: '',
  },
  {
    name: 'Four of Wands',
    rs: 'Wands',
    upRight: 'Peace, Marriage, Rest, Joy, Comfort, Reward',
    reversed: 'Criticism, Insecure, Restricted, Narrow Minded, Delay in Success',
    url: '',
  },
  {
    name: 'Five of Wands',
    rs: 'Wands',
    upRight: 'Challenge, Proving Yourself, Obstacles, Quarrels, Fighting, Delays, Stress',
    reversed: 'Opportunities, Internal Conflict, Overwhelm, Avoiding Conflict, Passive Aggressive',
    url: '',
  },
  {
    name: 'Six of Wands',
    rs: 'Wands',
    upRight: 'Success, Accomplishment, Reward, Confidence, Progress, Promotion, Winning',
    reversed: 'Feeling Deflated, Lack of Confidence, Delays, Egotistical, Taking a step back',
    url: '',
  },
  {
    name: 'Seven of Wands',
    rs: 'Wands',
    upRight: 'At an Advantage, Taking a Stand, Courageous, Challenge, Determined',
    reversed: 'Giving up, Anxiety, Allow things to unfold, Not where you want to be, Uncertain',
    url: '',
  },
  {
    name: 'Eight of Wands',
    rs: 'Wands',
    upRight: 'Moving Forward, Quick Action, Fast Progress, Moving, Change, Travel',
    reversed: 'Not in Control, Moving too fast, Miscommunication, Issues with plans or travel, Feeling Overwhelmed',
    url: '',
  },
  {
    name: 'Nine of Wands',
    rs: 'Wands',
    upRight: 'Faith, Persistence, Protecting yourself, Determined, Strength, Final Challenge',
    reversed: 'Weak, Inadequate, Scared, Helpless, Unsure, Tired, Overwhelmed',
    url: '',
  },
  {
    name: 'Ten of Wands',
    rs: 'Wands',
    upRight: 'Total Effort, Pressure, Heavy Load, Completion, Overworking, Burden',
    reversed: 'Stress Relief, Others Burden, Out of Energy, Letting go, Delegating work',
    url: '',
  },
  {
    name: 'Page of Wands',
    rs: 'Wands',
    upRight: 'Passion, Excitement, Enjoy life, Courage, Growth, Good News',
    reversed: 'Unhappy, Bad News, Impulsive, Trouble, Unreliable',
    url: '',
  },
  {
    name: 'Knight of Wands',
    rs: 'Wands',
    upRight: 'Cahnge is here, Creativity, New Experiences, New Ideas, Relocation, Action, Optimism, Adventure',
    reversed: 'Impatient, Indecision, Stress, Violence, No Energy, Frustration, Arguments',
    url: '',
  },
  {
    name: 'Queen of Wands',
    rs: 'Wands',
    upRight: 'Courageous, Ambitious, Leadership, Passion, Self-love, Organized, Confident',
    reversed: 'Egotistical, Jealous, Competetive, Moody, Irritated, Dominating',
    url: '',
  },
  {
    name: 'King of Wands',
    rs: 'Wands',
    upRight: 'Leader, Strength, Ambitious, Impulsive, Entrepreneur, Do it',
    reversed: 'Bossy, Arrogant, Aggresive, Selfish, Hot Tempered',
    url: '',
  },
  {
    name: 'Ace of Cups',
    rs: 'Cups',
    upRight: 'Renewed Emotions, Love, Happiness, Sensitivity, Creativity, Abundance',
    reversed: 'Feeling unloved, Rejection, Unhappy, Loss, Manipulation, Relationship Issues',
    url: '',
  },
  {
    name: 'Two of Cups',
    rs: 'Cups',
    upRight: 'Uniting, Sharring, Attraction, Partnership, Love, Trusting',
    reversed: 'Relationship Ending, Dislike, Leaving, Distrust, Self Love',
    url: '',
  },
  {
    name: 'Three of Cups',
    rs: 'Cups',
    upRight: 'Togetherness, Celebration, Thankful, Abundance, Playful, Fun, Trust',
    reversed: 'Excess, Selfish, Withdrawn, Endings, Independence',
    url: '',
  },
  {
    name: 'Four of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Five of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Six of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Seven of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Eight of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Nine of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Ten of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Page of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Knight of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Queen of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'King of Cups',
    rs: 'Cups',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Ace of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Two of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Three of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Four of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Five of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Six of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Seven of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Eight of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Nine of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Ten of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Page of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Knight of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Queen of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'King of Swords',
    rs: 'Swords',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Ace of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Two of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Three of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Four of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Five of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Six of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Seven of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Eight of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Nine of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Ten of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Page of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Knight of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'Queen of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
  {
    name: 'King of Pentacles',
    rs: 'Pentacles',
    upRight: '',
    reversed:'',
    url: '',
  },
]

export default deck;
